### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec  on opening file

### ISSUE THREAD

**Issue by svincena** [BaPSF/bapsflib#99]
for a particular file, there is a UnicodeDecodeError upon opening the file.
The file can be read with MATLAB scripts and looks OK with the hdfview java reader.

This is the file:
f="/data/BAPSF_Data/Chen/February2023/20_61x1line_UL1sweep_600G_2023-02-10_08.38.14.hdf5"

f=lapd.File(fname)
Traceback (most recent call last):

  File "/var/folders/1z/g2pbyskn6kq15v88mgq3twxh0000gn/T/ipykernel_77644/3119989713.py", line 1, in <module>
    f=lapd.File(fname)

  File "/Users/vincena/opt/anaconda3/lib/python3.9/site-packages/bapsflib/lapd/_hdf/file.py", line 44, in __init__
    super().__init__(

  File "/Users/vincena/opt/anaconda3/lib/python3.9/site-packages/bapsflib/_hdf/utils/file.py", line 94, in __init__
    self._build_info()

  File "/Users/vincena/opt/anaconda3/lib/python3.9/site-packages/bapsflib/lapd/_hdf/file.py", line 63, in _build_info
    self.info.update(self.file_map.run_info)

  File "/Users/vincena/opt/anaconda3/lib/python3.9/site-packages/bapsflib/lapd/_hdf/lapdmap.py", line 132, in run_info
    val = _bytes_to_str(val)

  File "/Users/vincena/opt/anaconda3/lib/python3.9/site-packages/bapsflib/utils/__init__.py", line 27, in _bytes_to_str
    return str(string, "utf-8")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1245: invalid start byte

++++++++++++++++++++++

conda list bapsflib
# packages in environment at /Users/vincena/opt/anaconda3:
#
# Name                    Version                   Build  Channel
bapsflib                  2.0.0b1                  pypi_0    pypi

In case this could be an hdf problem:
% conda list hdf5  
# packages in environment at /Users/vincena/opt/anaconda3:
#

# Name                    Version                   Build  Channel
hdf5                      1.10.6               hdbbcd12_0

**Comment by rocco8773** [comment]
See my comments on #100
